#!/bin/bash
if [ -z "$1" ]; then 
  echo usage: $0 testNumber jvmName
  exit
 fi
java -ea -cp 'jars/*' -Djava.security.manager \
     -Djava.security.policy=policies/dcvm.policy \
     fr.upmc.gaspardleo.test.DistributedTest $1 config.xml
